### ISSUE TITLE
Unexpected inner loop exception

### ISSUE THREAD

**Issue by sfcgeorge** [twalpole/apparition#18]
Firstly, thank you for making this. Years of Selenium's and Chromedriver's nonsense has worn me down. Apparition really seems like an improvement. I switched eola's whole test suite over (hundreds of tests) and it mostly seems to be working now, faster of course.

This is an odd little issue I've noticed. It doesn't actually cause specs to fail so it's not urgent, this message just gets printed as the suite runs. Not really sure what's going on.

```
Unexpected inner loop exception: undefined method `[]' for nil:NilClass: undefined method `[]' for nil:NilClass: ["/Users/sfcgeorge/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/apparition-0.3.0/lib/capybara/apparition/page.rb:609:in `block in register_js_error_handler'", "/Users/sfcgeorge/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/apparition-0.3.0/lib/capybara/apparition/driver/chrome_client.rb:209:in `block in process_handlers'", "/Users/sfcgeorge/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/apparition-0.3.0/lib/capybara/apparition/driver/chrome_client.rb:207:in `each'", "/Users/sfcgeorge/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/apparition-0.3.0/lib/capybara/apparition/driver/chrome_client.rb:207:in `process_handlers'", "/Users/sfcgeorge/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/apparition-0.3.0/lib/capybara/apparition/driver/chrome_client.rb:185:in `block in process_messages'", "/Users/sfcgeorge/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/apparition-0.3.0/lib/capybara/apparition/driver/chrome_client.rb:175:in `loop'", "/Users/sfcgeorge/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/apparition-0.3.0/lib/capybara/apparition/driver/chrome_client.rb:175:in `process_messages'", "/Users/sfcgeorge/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/apparition-0.3.0/lib/capybara/apparition/driver/chrome_client.rb:215:in `block in start_threads'"]
```

**Comment by twalpole** [comment]
This is an error message coming from one of the message handling threads and would happen during a JS error being thrown from your app (I think).  Any idea what JS error your app would be throwing? (If you set `DEBUG=V` environment variable before running your tests it'll dump a ton of info.  The item of interest would be a message of type `Runtime.exceptionThrown`

**Comment by sfcgeorge** [comment]
Ooh thank you. I believe it was something like `DOMException` without any more information, but I'll try DEBUG and get back to you.

**Comment by sfcgeorge** [comment]
Ok I copied all the output and grepped `pbpaste | grep "inner loop" -C 50`, so here's 50 lines surrounding the original message.

It looks like an error loading a font is causing it? I don't really care that the fonts don't load, ugly is fine. I did disable loading images, maybe that has something to do with it.

```
1560891826: got msg: {"method"=>"Target.receivedMessageFromTarget", "params"=>{"sessionId"=>"0C62CAF7B21AF92EE181B66823148A6B", "message"=>"{\"method\":\"Network.requestWillBeSent\",\"params\":{\"requestId\":\"1000048066.99\",\"loaderId\":\"A4F5BEF7310CF99EC5391D1DB1A1AE86\",\"documentURL\":\"http://compass.lvh.me:64420/outlets/steele-watersports-centre/time_slots\",\"request\":{\"url\":\"http://lvh.me:64420/font/Poppins/Poppins-400.ttf\",\"method\":\"GET\",\"headers\":{\"User-Agent\":\"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_5) AppleWebKit/537.36 (KHTML, like Gecko) HeadlessChrome/75.0.3770.100 Safari/537.36\",\"Referer\":\"http://lvh.me:64420/assets/core-cfe286057ad7ad30b61077b9246db390fca91865c23ffcc20f47d2ffc3bf2a32.css\",\"Origin\":\"http://compass.lvh.me:64420\"},\"mixedContentType\":\"none\",\"initialPriority\":\"VeryHigh\",\"referrerPolicy\":\"no-referrer-when-downgrade\"},\"timestamp\":200905.08298,\"wallTime\":1560891826.52906,\"initiator\":{\"type\":\"parser\",\"url\":\"http://compass.lvh.me:64420/outlets/steele-watersports-centre/time_slots\",\"lineNumber\":0},\"type\":\"Font\",\"frameId\":\"19E2E4D4B284C8668F3C1664BA3F5448\",\"hasUserGesture\":false}}", "targetId"=>"19E2E4D4B284C8668F3C1664BA3F5448"}}
1560891826: got msg: {"method"=>"Target.receivedMessageFromTarget", "params"=>{"sessionId"=>"0C62CAF7B21AF92EE181B66823148A6B", "message"=>"{\"method\":\"Network.loadingFailed\",\"params\":{\"requestId\":\"1000048066.98\",\"timestamp\":200905.083101,\"type\":\"Font\",\"errorText\":\"net::ERR_FAILED\",\"canceled\":false}}", "targetId"=>"19E2E4D4B284C8668F3C1664BA3F5448"}}
1560891826: got msg: {"id"=>406, "result"=>{}}
broadcasting response to 406
1560891826: got msg: {"method"=>"Target.receivedMessageFromTarget", "params"=>{"sessionId"=>"0C62CAF7B21AF92EE181B66823148A6B", "message"=>"{\"id\":405,\"result\":{}}", "targetId"=>"19E2E4D4B284C8668F3C1664BA3F5448"}}
Popped event Target.receivedMessageFromTarget
Calling handler for Network.requestWillBeSent
Calling handler for Network.requestWillBeSent
Cleaning up response for 406
broadcasting response to 405
1560891826: got msg: {"id"=>408, "result"=>{}}
broadcasting response to 408
1560891826: got msg: {"method"=>"Target.receivedMessageFromTarget", "params"=>{"sessionId"=>"0C62CAF7B21AF92EE181B66823148A6B", "message"=>"{\"id\":407,\"result\":{}}", "targetId"=>"19E2E4D4B284C8668F3C1664BA3F5448"}}
broadcasting response to 407
1560891826: got msg: {"id"=>410, "result"=>{}}
broadcasting response to 410
Popped event Target.receivedMessageFromTarget
Calling handler for Network.loadingFailed
Popped event Target.receivedMessageFromTarget
Popped event Target.receivedMessageFromTarget
1560891826: got msg: {"method"=>"Target.receivedMessageFromTarget", "params"=>{"sessionId"=>"0C62CAF7B21AF92EE181B66823148A6B", "message"=>"{\"id\":409,\"result\":{}}", "targetId"=>"19E2E4D4B284C8668F3C1664BA3F5448"}}
Popped event Target.receivedMessageFromTarget
Cleaning up response for 405
Cleaning up response for 408
Cleaning up response for 407
Cleaning up response for 410
broadcasting response to 409
1560891826: got msg: {"id"=>412, "result"=>{}}
Cleaning up response for 409
broadcasting response to 412
1560891826: got msg: {"method"=>"Target.receivedMessageFromTarget", "params"=>{"sessionId"=>"0C62CAF7B21AF92EE181B66823148A6B", "message"=>"{\"id\":411,\"result\":{\"result\":{\"type\":\"object\",\"subtype\":\"array\",\"className\":\"Array\",\"description\":\"Array(0)\",\"objectId\":\"{\\\"injectedScriptId\\\":3,\\\"id\\\":35}\"}}}", "targetId"=>"19E2E4D4B284C8668F3C1664BA3F5448"}}
broadcasting response to 411
1560891826: got msg: {"id"=>414, "result"=>{}}
Processed msg: 411 in 0.035006 seconds
1560891826: sending msg: {"method":"Target.sendMessageToTarget","params":{"sessionId":"0C62CAF7B21AF92EE181B66823148A6B","message":"{\"method\":\"Runtime.getProperties\",\"params\":{\"objectId\":\"{\\\"injectedScriptId\\\":3,\\\"id\\\":35}\",\"ownProperties\":true},\"id\":415}"},"id":416}
Popped event Target.receivedMessageFromTarget
broadcasting response to 414
1560891826: got msg: {"method"=>"Target.receivedMessageFromTarget", "params"=>{"sessionId"=>"0C62CAF7B21AF92EE181B66823148A6B", "message"=>"{\"method\":\"Network.loadingFailed\",\"params\":{\"requestId\":\"1000048066.84\",\"timestamp\":200905.095763,\"type\":\"Font\",\"errorText\":\"net::ERR_FAILED\",\"canceled\":false}}", "targetId"=>"19E2E4D4B284C8668F3C1664BA3F5448"}}
Popped event Target.receivedMessageFromTarget
Calling handler for Network.loadingFailed
Cleaning up response for 414
1560891826: got msg: {"method"=>"Target.receivedMessageFromTarget", "params"=>{"sessionId"=>"0C62CAF7B21AF92EE181B66823148A6B", "message"=>"{\"id\":413,\"result\":{}}", "targetId"=>"19E2E4D4B284C8668F3C1664BA3F5448"}}
broadcasting response to 413
Popped event Target.receivedMessageFromTarget
Cleaning up response for 413
1560891826: got msg: {"method"=>"Target.receivedMessageFromTarget", "params"=>{"sessionId"=>"0C62CAF7B21AF92EE181B66823148A6B", "message"=>"{\"method\":\"Runtime.exceptionThrown\",\"params\":{\"timestamp\":1560891826542.052,\"exceptionDetails\":{\"exceptionId\":1,\"text\":\"Uncaught (in promise)\",\"lineNumber\":0,\"columnNumber\":0,\"scriptId\":\"1\",\"url\":\"http://compass.lvh.me:64420/outlets/steele-watersports-centre/time_slots\",\"exception\":{\"type\":\"object\",\"subtype\":\"error\",\"className\":\"DOMException\",\"description\":\"DOMException\",\"objectId\":\"{\\\"injectedScriptId\\\":3,\\\"id\\\":36}\",\"preview\":{\"type\":\"object\",\"subtype\":\"error\",\"description\":\"DOMException\",\"overflow\":false,\"properties\":[{\"name\":\"code\",\"type\":\"number\",\"value\":\"19\"},{\"name\":\"name\",\"type\":\"string\",\"value\":\"NetworkError\"},{\"name\":\"message\",\"type\":\"string\",\"value\":\"A network error occurred.\"}]}},\"executionContextId\":3}}}", "targetId"=>"19E2E4D4B284C8668F3C1664BA3F5448"}}
Popped event Target.receivedMessageFromTarget
1560891826: got msg: {"method"=>"Target.receivedMessageFromTarget", "params"=>{"sessionId"=>"0C62CAF7B21AF92EE181B66823148A6B", "message"=>"{\"method\":\"Network.loadingFailed\",\"params\":{\"requestId\":\"1000048066.93\",\"timestamp\":200905.108226,\"type\":\"Font\",\"errorText\":\"net::ERR_FAILED\",\"canceled\":false}}", "targetId"=>"19E2E4D4B284C8668F3C1664BA3F5448"}}
Calling handler for Runtime.exceptionThrown
1560891826: got msg: {"method"=>"Target.receivedMessageFromTarget", "params"=>{"sessionId"=>"0C62CAF7B21AF92EE181B66823148A6B", "message"=>"{\"method\":\"Network.requestIntercepted\",\"params\":{\"interceptionId\":\"interception-job-39.0\",\"request\":{\"url\":\"http://lvh.me:64420/font/Poppins/Poppins-700.woff\",\"method\":\"GET\",\"headers\":{\"Origin\":\"http://compass.lvh.me:64420\",\"User-Agent\":\"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_5) AppleWebKit/537.36 (KHTML, like Gecko) HeadlessChrome/75.0.3770.100 Safari/537.36\",\"Accept\":\"*/*\",\"Referer\":\"http://lvh.me:64420/assets/core-cfe286057ad7ad30b61077b9246db390fca91865c23ffcc20f47d2ffc3bf2a32.css\"},\"initialPriority\":\"VeryHigh\",\"referrerPolicy\":\"no-referrer-when-downgrade\"},\"frameId\":\"19E2E4D4B284C8668F3C1664BA3F5448\",\"resourceType\":\"Font\",\"isNavigationRequest\":false,\"requestId\":\"1000048066.104\"}}", "targetId"=>"19E2E4D4B284C8668F3C1664BA3F5448"}}
Unexpected inner loop exception: undefined method `[]' for nil:NilClass: undefined method `[]' for nil:NilClass: ["/Users/sfcgeorge/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/apparition-0.3.0/lib/capybara/apparition/page.rb:609:in `block in register_js_error_handler'", "/Users/sfcgeorge/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/apparition-0.3.0/lib/capybara/apparition/driver/chrome_client.rb:209:in `block in process_handlers'", "/Users/sfcgeorge/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/apparition-0.3.0/lib/capybara/apparition/driver/chrome_client.rb:207:in `each'", "/Users/sfcgeorge/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/apparition-0.3.0/lib/capybara/apparition/driver/chrome_client.rb:207:in `process_handlers'", "/Users/sfcgeorge/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/apparition-0.3.0/lib/capybara/apparition/driver/chrome_client.rb:185:in `block in process_messages'", "/Users/sfcgeorge/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/apparition-0.3.0/lib/capybara/apparition/driver/chrome_client.rb:175:in `loop'", "/Users/sfcgeorge/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/apparition-0.3.0/lib/capybara/apparition/driver/chrome_client.rb:175:in `process_messages'", "/Users/sfcgeorge/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/apparition-0.3.0/lib/capybara/apparition/driver/chrome_client.rb:215:in `block in start_threads'"]
Popped event Target.receivedMessageFromTarget
Calling handler for Network.loadingFailed
1560891826: got msg: {"method"=>"Target.receivedMessageFromTarget", "params"=>{"sessionId"=>"0C62CAF7B21AF92EE181B66823148A6B", "message"=>"{\"method\":\"Network.requestWillBeSent\",\"params\":{\"requestId\":\"1000048066.104\",\"loaderId\":\"A4F5BEF7310CF99EC5391D1DB1A1AE86\",\"documentURL\":\"http://compass.lvh.me:64420/outlets/steele-watersports-centre/time_slots\",\"request\":{\"url\":\"http://lvh.me:64420/font/Poppins/Poppins-700.woff\",\"method\":\"GET\",\"headers\":{\"User-Agent\":\"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_5) AppleWebKit/537.36 (KHTML, like Gecko) HeadlessChrome/75.0.3770.100 Safari/537.36\",\"Referer\":\"http://lvh.me:64420/assets/core-cfe286057ad7ad30b61077b9246db390fca91865c23ffcc20f47d2ffc3bf2a32.css\",\"Origin\":\"http://compass.lvh.me:64420\"},\"mixedContentType\":\"none\",\"initialPriority\":\"VeryHigh\",\"referrerPolicy\":\"no-referrer-when-downgrade\"},\"timestamp\":200905.108511,\"wallTime\":1560891826.55459,\"initiator\":{\"type\":\"parser\",\"url\":\"http://compass.lvh.me:64420/outlets/steele-watersports-centre/time_slots\",\"lineNumber\":0},\"type\":\"Font\",\"frameId\":\"19E2E4D4B284C8668F3C1664BA3F5448\",\"hasUserGesture\":false}}", "targetId"=>"19E2E4D4B284C8668F3C1664BA3F5448"}}
1560891826: got msg: {"method"=>"Target.receivedMessageFromTarget", "params"=>{"sessionId"=>"0C62CAF7B21AF92EE181B66823148A6B", "message"=>"{\"method\":\"Network.loadingFailed\",\"params\":{\"requestId\":\"1000048066.103\",\"timestamp\":200905.108625,\"type\":\"Font\",\"errorText\":\"net::ERR_FAILED\",\"canceled\":false}}", "targetId"=>"19E2E4D4B284C8668F3C1664BA3F5448"}}
Popped event Target.receivedMessageFromTarget
Calling handler for Network.requestIntercepted
1560891826: sending msg: {"method":"Target.sendMessageToTarget","params":{"sessionId":"0C62CAF7B21AF92EE181B66823148A6B","message":"{\"method\":\"Network.continueInterceptedRequest\",\"params\":{\"interceptionId\":\"interception-job-39.0\",\"headers\":{\"Origin\":\"http://compass.lvh.me:64420\",\"User-Agent\":\"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_5) AppleWebKit/537.36 (KHTML, like Gecko) HeadlessChrome/75.0.3770.100 Safari/537.36\",\"Accept\":\"*/*\",\"Referer\":\"http://lvh.me:64420/assets/core-cfe286057ad7ad30b61077b9246db390fca91865c23ffcc20f47d2ffc3bf2a32.css\"}},\"id\":417}"},"id":418}
1560891826: got msg: {"method"=>"Target.receivedMessageFromTarget", "params"=>{"sessionId"=>"0C62CAF7B21AF92EE181B66823148A6B", "message"=>"{\"method\":\"Network.requestIntercepted\",\"params\":{\"interceptionId\":\"interception-job-40.0\",\"request\":{\"url\":\"http://lvh.me:64420/font/Chivo/Chivo-300.woff\",\"method\":\"GET\",\"headers\":{\"Origin\":\"http://compass.lvh.me:64420\",\"User-Agent\":\"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_5) AppleWebKit/537.36 (KHTML, like Gecko) HeadlessChrome/75.0.3770.100 Safari/537.36\",\"Accept\":\"*/*\",\"Referer\":\"http://lvh.me:64420/assets/core-cfe286057ad7ad30b61077b9246db390fca91865c23ffcc20f47d2ffc3bf2a32.css\"},\"initialPriority\":\"VeryHigh\",\"referrerPolicy\":\"no-referrer-when-downgrade\"},\"frameId\":\"19E2E4D4B284C8668F3C1664BA3F5448\",\"resourceType\":\"Font\",\"isNavigationRequest\":false,\"requestId\":\"1000048066.86\"}}", "targetId"=>"19E2E4D4B284C8668F3C1664BA3F5448"}}
1560891826: got msg: {"method"=>"Target.receivedMessageFromTarget", "params"=>{"sessionId"=>"0C62CAF7B21AF92EE181B66823148A6B", "message"=>"{\"method\":\"Network.loadingFailed\",\"params\":{\"requestId\":\"1000048066.99\",\"timestamp\":200905.125946,\"type\":\"Font\",\"errorText\":\"net::ERR_FAILED\",\"canceled\":false}}", "targetId"=>"19E2E4D4B284C8668F3C1664BA3F5448"}}
Popped event Target.receivedMessageFromTarget
Calling handler for Network.requestWillBeSent
Calling handler for Network.requestWillBeSent
Popped event Target.receivedMessageFromTarget
Calling handler for Network.loadingFailed
1560891826: got msg: {"method"=>"Target.receivedMessageFromTarget", "params"=>{"sessionId"=>"0C62CAF7B21AF92EE181B66823148A6B", "message"=>"{\"method\":\"Network.requestWillBeSent\",\"params\":{\"requestId\":\"1000048066.86\",\"loaderId\":\"A4F5BEF7310CF99EC5391D1DB1A1AE86\",\"documentURL\":\"http://compass.lvh.me:64420/outlets/steele-watersports-centre/time_slots\",\"request\":{\"url\":\"http://lvh.me:64420/font/Chivo/Chivo-300.woff\",\"method\":\"GET\",\"headers\":{\"User-Agent\":\"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_5) AppleWebKit/537.36 (KHTML, like Gecko) HeadlessChrome/75.0.3770.100 Safari/537.36\",\"Referer\":\"http://lvh.me:64420/assets/core-cfe286057ad7ad30b61077b9246db390fca91865c23ffcc20f47d2ffc3bf2a32.css\",\"Origin\":\"http://compass.lvh.me:64420\"},\"mixedContentType\":\"none\",\"initialPriority\":\"VeryHigh\",\"referrerPolicy\":\"no-referrer-when-downgrade\"},\"timestamp\":200905.126222,\"wallTime\":1560891826.5723,\"initiator\":{\"type\":\"parser\",\"url\":\"http://compass.lvh.me:64420/outlets/steele-watersports-centre/time_slots\",\"lineNumber\":0},\"type\":\"Font\",\"frameId\":\"19E2E4D4B284C8668F3C1664BA3F5448\",\"hasUserGesture\":false}}", "targetId"=>"19E2E4D4B284C8668F3C1664BA3F5448"}}
1560891826: got msg: {"method"=>"Target.receivedMessageFromTarget", "params"=>{"sessionId"=>"0C62CAF7B21AF92EE181B66823148A6B", "message"=>"{\"method\":\"Network.loadingFailed\",\"params\":{\"requestId\":\"1000048066.85\",\"timestamp\":200905.126354,\"type\":\"Font\",\"errorText\":\"net::ERR_FAILED\",\"canceled\":false}}", "targetId"=>"19E2E4D4B284C8668F3C1664BA3F5448"}}
1560891826: got msg: {"id"=>416, "result"=>{}}
Popped event Target.receivedMessageFromTarget
broadcasting response to 416
Calling handler for Network.requestIntercepted
1560891826: sending msg: {"method":"Target.sendMessageToTarget","params":{"sessionId":"0C62CAF7B21AF92EE181B66823148A6B","message":"{\"method\":\"Network.continueInterceptedRequest\",\"params\":{\"interceptionId\":\"interception-job-40.0\",\"headers\":{\"Origin\":\"http://compass.lvh.me:64420\",\"User-Agent\":\"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_5) AppleWebKit/537.36 (KHTML, like Gecko) HeadlessChrome/75.0.3770.100 Safari/537.36\",\"Accept\":\"*/*\",\"Referer\":\"http://lvh.me:64420/assets/core-cfe286057ad7ad30b61077b9246db390fca91865c23ffcc20f47d2ffc3bf2a32.css\"}},\"id\":419}"},"id":420}
Popped event Target.receivedMessageFromTarget
Calling handler for Network.loadingFailed
Popped event Target.receivedMessageFromTarget
Calling handler for Network.requestWillBeSent
Calling handler for Network.requestWillBeSent
Popped event Target.receivedMessageFromTarget
Calling handler for Network.loadingFailed
1560891826: got msg: {"method"=>"Target.receivedMessageFromTarget", "params"=>{"sessionId"=>"0C62CAF7B21AF92EE181B66823148A6B", "message"=>"{\"id\":415,\"result\":{\"result\":[{\"name\":\"length\",\"value\":{\"type\":\"number\",\"value\":0,\"description\":\"0\"},\"writable\":true,\"configurable\":false,\"enumerable\":false,\"isOwn\":true},{\"name\":\"__proto__\",\"value\":{\"type\":\"object\",\"subtype\":\"array\",\"className\":\"Array\",\"description\":\"Array(0)\",\"objectId\":\"{\\\"injectedScriptId\\\":3,\\\"id\\\":37}\"},\"writable\":true,\"configurable\":true,\"enumerable\":false,\"isOwn\":true}]}}", "targetId"=>"19E2E4D4B284C8668F3C1664BA3F5448"}}
broadcasting response to 415
Popped event Target.receivedMessageFromTarget
Processed msg: 415 in 0.007631 seconds
1560891826: got msg: {"method"=>"Target.receivedMessageFromTarget", "params"=>{"sessionId"=>"0C62CAF7B21AF92EE181B66823148A6B", "message"=>"{\"method\":\"Network.requestIntercepted\",\"params\":{\"interceptionId\":\"interception-job-41.0\",\"request\":{\"url\":\"http://lvh.me:64420/font/Chivo/Chivo-400.woff\",\"method\":\"GET\",\"headers\":{\"Origin\":\"http://compass.lvh.me:64420\",\"User-Agent\":\"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_5) AppleWebKit/537.36 (KHTML, like Gecko) HeadlessChrome/75.0.3770.100 Safari/537.36\",\"Accept\":\"*/*\",\"Referer\":\"http://lvh.me:64420/assets/core-cfe286057ad7ad30b61077b9246db390fca91865c23ffcc20f47d2ffc3bf2a32.css\"},\"initialPriority\":\"VeryHigh\",\"referrerPolicy\":\"no-referrer-when-downgrade\"},\"frameId\":\"19E2E4D4B284C8668F3C1664BA3F5448\",\"resourceType\":\"Font\",\"isNavigationRequest\":false,\"requestId\":\"1000048066.89\"}}", "targetId"=>"19E2E4D4B284C8668F3C1664BA3F5448"}}
Popped event Target.receivedMessageFromTarget
Calling handler for Network.requestIntercepted
1560891826: sending msg: {"method":"Target.sendMessageToTarget","params":{"sessionId":"0C62CAF7B21AF92EE181B66823148A6B","message":"{\"method\":\"Network.continueInterceptedRequest\",\"params\":{\"interceptionId\":\"interception-job-41.0\",\"headers\":{\"Origin\":\"http://compass.lvh.me:64420\",\"User-Agent\":\"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_5) AppleWebKit/537.36 (KHTML, like Gecko) HeadlessChrome/75.0.3770.100 Safari/537.36\",\"Accept\":\"*/*\",\"Referer\":\"http://lvh.me:64420/assets/core-cfe286057ad7ad30b61077b9246db390fca91865c23ffcc20f47d2ffc3bf2a32.css\"}},\"id\":421}"},"id":422}
1560891826: got msg: {"method"=>"Target.receivedMessageFromTarget", "params"=>{"sessionId"=>"0C62CAF7B21AF92EE181B66823148A6B", "message"=>"{\"method\":\"Network.requestWillBeSent\",\"params\":{\"requestId\":\"1000048066.89\",\"loaderId\":\"A4F5BEF7310CF99EC5391D1DB1A1AE86\",\"documentURL\":\"http://compass.lvh.me:64420/outlets/steele-watersports-centre/time_slots\",\"request\":{\"url\":\"http://lvh.me:64420/font/Chivo/Chivo-400.woff\",\"method\":\"GET\",\"headers\":{\"User-Agent\":\"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_5) AppleWebKit/537.36 (KHTML, like Gecko) HeadlessChrome/75.0.3770.100 Safari/537.36\",\"Referer\":\"http://lvh.me:64420/assets/core-cfe286057ad7ad30b61077b9246db390fca91865c23ffcc20f47d2ffc3bf2a32.css\",\"Origin\":\"http://compass.lvh.me:64420\"},\"mixedContentType\":\"none\",\"initialPriority\":\"VeryHigh\",\"referrerPolicy\":\"no-referrer-when-downgrade\"},\"timestamp\":200905.133685,\"wallTime\":1560891826.57976,\"initiator\":{\"type\":\"parser\",\"url\":\"http://compass.lvh.me:64420/outlets/steele-watersports-centre/time_slots\",\"lineNumber\":0},\"type\":\"Font\",\"frameId\":\"19E2E4D4B284C8668F3C1664BA3F5448\",\"hasUserGesture\":false}}", "targetId"=>"19E2E4D4B284C8668F3C1664BA3F5448"}}
1560891826: got msg: {"method"=>"Target.receivedMessageFromTarget", "params"=>{"sessionId"=>"0C62CAF7B21AF92EE181B66823148A6B", "message"=>"{\"method\":\"Network.loadingFailed\",\"params\":{\"requestId\":\"1000048066.88\",\"timestamp\":200905.133846,\"type\":\"Font\",\"errorText\":\"net::ERR_FAILED\",\"canceled\":false}}", "targetId"=>"19E2E4D4B284C8668F3C1664BA3F5448"}}
1560891826: got msg: {"id"=>418, "result"=>{}}
Popped event Target.receivedMessageFromTarget
Calling handler for Network.requestWillBeSent
broadcasting response to 418
1560891826: got msg: {"method"=>"Target.receivedMessageFromTarget", "params"=>{"sessionId"=>"0C62CAF7B21AF92EE181B66823148A6B", "message"=>"{\"id\":417,\"result\":{}}", "targetId"=>"19E2E4D4B284C8668F3C1664BA3F5448"}}
broadcasting response to 417
Calling handler for Network.requestWillBeSent
Popped event Target.receivedMessageFromTarget
Calling handler for Network.loadingFailed
Cleaning up response for 418
Cleaning up response for 417
Popped event Target.receivedMessageFromTarget
```

**Comment by twalpole** [comment]
Ok - so the relevant message is
```
1560891826: got msg: {"method"=>"Target.receivedMessageFromTarget", "params"=>{"sessionId"=>"0C62CAF7B21AF92EE181B66823148A6B", "message"=>"{\"method\":\"Runtime.exceptionThrown\",\"params\":{\"timestamp\":1560891826542.052,\"exceptionDetails\":{\"exceptionId\":1,\"text\":\"Uncaught (in promise)\",\"lineNumber\":0,\"columnNumber\":0,\"scriptId\":\"1\",\"url\":\"http://compass.lvh.me:64420/outlets/steele-watersports-centre/time_slots\",\"exception\":{\"type\":\"object\",\"subtype\":\"error\",\"className\":\"DOMException\",\"description\":\"DOMException\",\"objectId\":\"{\\\"injectedScriptId\\\":3,\\\"id\\\":36}\",\"preview\":{\"type\":\"object\",\"subtype\":\"error\",\"description\":\"DOMException\",\"overflow\":false,\"properties\":[{\"name\":\"code\",\"type\":\"number\",\"value\":\"19\"},{\"name\":\"name\",\"type\":\"string\",\"value\":\"NetworkError\"},{\"name\":\"message\",\"type\":\"string\",\"value\":\"A network error occurred.\"}]}},\"executionContextId\":3}}}", "targetId"=>"19E2E4D4B284C8668F3C1664BA3F5448"}}
```
which appears not to have a stackTrace entry.  Thanks for reporting this and providing the needed logging - I'll fix it tomorrow.
