### ISSUE TITLE
Node#click is flaky?

### ISSUE THREAD

**Issue by YusukeIwaki** [twalpole/apparition#76]
When I tried this Gem with the example spec below, Apprition driver passes only 8/10 where capybara selenium driver passes 10/10.

```ruby
RSpec.describe 'github search' do
  around do |example|
    prev_host = Capybara.app_host
    Capybara.app_host = 'https://github.com'
    begin
      example.run
    ensure
      Capybara.app_host = prev_host
    end
  end

  10.times { # repeat and repeat and repeat...!!
  it 'should search repository' do
    visit '/'

    fill_in('q', with: 'selenium')
    find('a[data-item-type="global_search"]').click

    output = all('.repo-list-item').map do |li|
      li.all('a').first.text
    end
    puts output
    expect(output).to include(match(/selenium/i))
  end
  }

end
```

```
Failures:

  1) github search should search repository
     Failure/Error: find('a[data-item-type="global_search"]').click
     
     Capybara::ElementNotFound:
       Unable to find visible css "a[data-item-type=\"global_search\"]"
     # ./spec/feature/github_search_spec.rb:44:in `block (2 levels) in <top (required)>'
     # ./spec/feature/github_search_spec.rb:8:in `block (2 levels) in <top (required)>'

  2) github search should search repository
     Failure/Error: find('a[data-item-type="global_search"]').click
     
     Capybara::ElementNotFound:
       Unable to find visible css "a[data-item-type=\"global_search\"]"
     # ./spec/feature/github_search_spec.rb:70:in `block (2 levels) in <top (required)>'
     # ./spec/feature/github_search_spec.rb:8:in `block (2 levels) in <top (required)>'
```

The link is shown only during the text field is focused.

<img width="350" alt="image" src="https://user-images.githubusercontent.com/11763113/119848673-f7be6c80-bf46-11eb-99dc-7879057648cb.png">

**Comment by YusukeIwaki** [comment]
Actually I found this problem in my Capybara driver development (capybara-playwright-driver).
This issue is also reproduced with [cuprite](https://github.com/rubycdp/cuprite).

I don't know detailed cause but it seems that `visible?` checks the node visibility with JS, which can be evaluated **without attached to the DOM**. So I avoided this problem by adding an assertion of node staleness, before executing JS for checking visibility.
https://github.com/YusukeIwaki/capybara-playwright-driver/pull/31

**Comment by nathan-appere** [comment]
Related: got bitten by Bootstrap 5 default `scroll-behavior: smooth;` when focusing on inputs!
